manifest:
  version: 1.2
  defaults:
    remote: cormoran
    revision: main
  remotes:
    - name: zmkfirmware
      url-base: https://github.com/zmkfirmware
    - name: sekigon-gonnoc
      url-base: https://github.com/sekigon-gonnoc
    - name: gohanda11
      url-base: https://github.com/gohanda11
    - name: cormoran
      url-base: https://github.com/cormoran
  projects:
    - name: zmk
      remote: zmkfirmware
      import:
        file: app/west.yml
        path-prefix: external
      clone-depth: 1
    - name: zmk-feature-non-lipo-battery-management
      remote: sekigon-gonnoc
      path: external/zmk-feature-non-lipo-battery-management
      clone-depth: 1
    - name: zmk-pmw3610-driver
      remote: gohanda11
      path: external/zmk-pmw3610-driver
      clone-depth: 1
  self:
    path: config
